#!/usr/bin/env python
"""Compare beta-sweep runs into one Markdown table.

Reads results/runs/*/evals/{margin_base,margin_dpo,judge_labels,mmlu_*.json}
and writes results/beta_comparison.md. Missing files are shown as "-",
never invented.
"""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
RUNS = sorted((ROOT / "results" / "runs").glob("beta_*"))


def read_json(path: Path):
    if path.exists():
        return json.loads(path.read_text(encoding="utf-8"))
    return None


def main() -> None:
    rows = []
    for run in RUNS:
        ev = run / "evals"
        mb = read_json(ev / "margin_base.json") or {}
        md = read_json(ev / "margin_dpo.json") or {}
        judge = read_json(ev / "judge_labels.json") or {}
        mmlu_b = read_json(ev / "mmlu_base.json") or {}
        mmlu_d = read_json(ev / "mmlu_dpo.json") or {}

        def fmt(x, nd=3):
            return f"{x:.{nd}f}" if isinstance(x, (int, float)) else "-"

        rows.append({
            "run": run.name,
            "beta": fmt(md.get("beta")),
            "margin_base": fmt(mb.get("accuracy")),
            "margin_dpo": fmt(md.get("accuracy")),
            "mean_margin": fmt(md.get("mean_margin"), 4),
            "win_rate": fmt(judge.get("overall")),
            "win_dpo_longer": fmt(judge.get("when_dpo_longer")),
            "win_base_longer": fmt(judge.get("when_base_longer")),
            "judge": judge.get("judge_model", "-"),
            "mmlu_base": fmt(mmlu_b.get("acc")),
            "mmlu_dpo": fmt(mmlu_d.get("acc")),
        })

    lines = ["# Beta sweep comparison", "",
             "Generated by scripts/05_compare_betas.py. Empty cells mean the "
             "eval did not run or its file is missing. Nothing is invented.",
             "",
             "| run | beta | margin acc (base) | margin acc (dpo) | "
             "mean margin | win rate | win (dpo longer) | win (base longer) | "
             "judge | mmlu (base) | mmlu (dpo) |",
             "|---|---|---|---|---|---|---|---|---|---|---|"]
    for r in rows:
        lines.append(
            f"| {r['run']} | {r['beta']} | {r['margin_base']} | "
            f"{r['margin_dpo']} | {r['mean_margin']} | {r['win_rate']} | "
            f"{r['win_dpo_longer']} | {r['win_base_longer']} | {r['judge']} | "
            f"{r['mmlu_base']} | {r['mmlu_dpo']} |")
    lines += ["",
              "How to read it: margin acc (dpo) should beat margin acc "
              "(base); if it does not, the run failed. Win rate near 0.5 is "
              "noise. A large mmlu drop invalidates the run. See EVAL-PLAN.md."]
    out = ROOT / "results" / "beta_comparison.md"
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {out} ({len(rows)} runs)")


if __name__ == "__main__":
    main()
